AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::640615917264:role/service-role/search-photos-role-y4bwfg2q'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Tags:
        'lambda:createdBy': SAM
      Layers:
        - 'arn:aws:lambda:us-east-1:640615917264:layer:Python:6'
